version: '3.9'

services:
  backend:
    build: ./backend
    container_name: ai-audiosense-backend
    ports:
      - "8000:8000"
    networks:
      - ai-audiosense-net

  frontend:
    build: ./frontend
    container_name: ai-audiosense-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ai-audiosense-net

networks:
  ai-audiosense-net:
    driver: bridge
